### ISSUE TITLE
I dont see the time values in the dialog

### ISSUE THREAD

**Issue by pivocoder** [troberts-28/react-native-timer-picker#43]
Since I updated in my expo to a newer react version I have issues with the selection of the time. Once I scroll I see numbers but before they are blank. 

![Bildschirmfoto vom 2024-12-01 15-38-27](https://github.com/user-attachments/assets/a69f3ff4-05ad-4bb9-9a57-7b106f5546da)

 ```
<TimerPickerModal
        visible={showPickerExecution}
        setIsVisible={setShowPickerExecution}
        onConfirm={(pickedDuration) => {
          timeAsana.set(getTotalSecondsOfTimeSelection(pickedDuration), 0);
          setShowPickerExecution(false);
          setShowPickerObserving(true);
        }}
        styles={{
          theme: "light",
        }}
        initialValue={{
          hours: executionTime.hours ? parseInt(executionTime.hours) : 0,
          minutes: executionTime.minutes ? parseInt(executionTime.minutes) : 0,
          seconds: executionTime.seconds ? parseInt(executionTime.seconds) : 0,
        }}
        modalTitle="Set Execution Time"
        closeOnOverlayPress
        LinearGradient={LinearGradient}
        modalProps={{
          overlayOpacity: 0.2,
        }}
      />
```

 "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.3",

**Comment by troberts-28** [comment]
Hey @pivocoder,
 
Thanks for raising this, will take a look ASAP. Just to confirm, are you on Expo SDK 52, and react-native-timer-picker v2.0.0?

**Comment by pivocoder** [comment]
Yes, I'm using "expo": "^52.0.11", and  "react-native-timer-picker": "^2.0.0", are in my package.json :). I run into this issue because I have updated my expo sdk. Thanks for the quick answer

**Comment by troberts-28** [comment]
Hey @pivocoder,

I've just released a patch (`v2.0.1`) that  may (or may not!) address your issues. The patch fixes two things:
- NaN inputs to initial values (and other variables) breaking the picker.
- Pickers sometimes not snapping to values. This was caused by a slight change in RN's FlatList between `v0.74` and `v0.76`. Although the behaviour is not the same, I wonder if this might have been the underlying cause of your issue.

In any case, try out `v2.0.1` and let me know if it solves your issue!

**Comment by troberts-28** [comment]
Can't see anything obviously wrong with your setup. Unrelated but `@types/react` and `typescript` should both be in your 
devDependencies 😇

But that context you gave about opening and closing the modal will help me track it down. Will take another look and get back to you.

**Comment by troberts-28** [comment]
Still struggling to reproduce this. I've created an Expo Snack that mirrors your setup - can you reproduce it in here?

https://snack.expo.dev/@nuumi/issue-43-demo

**Comment by troberts-28** [comment]
Hey @pivocoder, just checking in on this. Were you able to reproduce the issue in the Snack?

**Comment by pivocoder** [comment]
Hi @troberts-28,

sorry for my late response. I was able to reproduce the issue in your snack. 
![grafik](https://github.com/user-attachments/assets/0e4edf95-89fa-49c5-ab4f-71c00ebecd80)

**Comment by troberts-28** [comment]
Ah I should have asked what platform you were on! It's something Android-specific (hence why I wasn't able to reproduce initially). Should be able to figure out the problem now - will keep you updated on my progress.

**Comment by ssachtleben** [comment]
This fixed also my entries vanishing on ios after fast scrolling with v2.0.0.

Thanks for the fix 🙏

**Comment by ssachtleben** [comment]
@troberts-28 unfortunately adding the picker container styles as you suggested has no impact, the problem is still happening.

**Comment by troberts-28** [comment]
Hey @ssachtleben, looking into this now. Could you just share the props you're providing to the `TimerPickerModal` to help me reproduce it?

**Comment by ssachtleben** [comment]
> Hey [@ssachtleben](https://github.com/ssachtleben), looking into this now. Could you just share the props you're providing to the `TimerPickerModal` to help me reproduce it?

@troberts-28 sure here you go:

```
                    <TimerPickerModal
                        visible={showPicker}
                        setIsVisible={setShowPicker}
                        onConfirm={async (pickedDuration) => {
                            console.log(pickedDuration);
                            workoutExerciseSet.time = pickedDuration.hours * 3600 + pickedDuration.minutes * 60 + pickedDuration.seconds;
                            await WorkoutExerciseSet.update(workoutExerciseSet);
                            setShowPicker(false);

                            const newWorkoutExerciseSets = await WorkoutExerciseSet.findByWorkoutId(workout.id);
                            setWorkoutExerciseSets(newWorkoutExerciseSets);
                        }}
                        initialValue={parseTime(workoutExerciseSet.time?.toString())}
                        //modalTitle="Set Time"
                        onCancel={() => setShowPicker(false)}
                        //disableInfiniteScroll
                        closeOnOverlayPress
                        Audio={Audio}
                        LinearGradient={LinearGradient}
                        Haptics={Haptics}
                        styles={{
                            theme: "dark",
                            pickerContainer: {
                                width: 240, // set this to your desired width
                                justifyContent: "center",
                                alignItems: "center",
                            },
                        }}
                        modalProps={{
                            overlayOpacity: 0.2,
                        }}
                    />
```

**Comment by ssachtleben** [comment]
> Another question I have is in the video at the end you see I try to wanna use the picker with transparent background but then the gradient is gone. It would be so great if this could fade into transparent.

Ah I guess it's not possible since you fade from that color into transparent. So I cannot use faded out into the gradient 😞

**Comment by troberts-28** [comment]
@ssachtleben thanks for the investigative work! Will take a look today and see if I can get to the bottom of this. Will keep you updated on my progress.

On your other points:
1. This is an interesting point! You're right that it currently relies on the background colour so it isn't currently possibly to have it fade out with a transparent background. I have just figured out how to make this work using a [MaskedView](https://www.npmjs.com/package/@react-native-masked-view/masked-view) (see below). I don't want to add it as a dependency for the project, but will make it possible to supply it as a prop (like LinearGradient).

<img src="https://github.com/user-attachments/assets/31b4b224-e01d-419e-845f-821acde3508b" width="300">

2. I've had this thought too! It does turn it into a different project but it could well be worth doing. I think my plan would be:

- Create a new library (e.g. `react-native-infinite-picker`), which only contains a generic version of the core infinite picker component (currently called `DurationScroll` in this project).
- That library will fulfill the need for any type of picker (e.g. date and height inputs) as it will be up to the user to supply the list of items for each picker. 
- Adjust this library to use the new generic picker library.

What do you think? Let me know if you'd like to get involved in it.

**Comment by troberts-28** [comment]
@ssachtleben still struggling to reproduce the issue... Can you:

1. Share your `package.json` so I can match your versions exactly.
2. Let me know if you're on the new architecture or not?

**Comment by ssachtleben** [comment]
> What do you think? Let me know if you'd like to get involved in it.

I would love to. But I'm super busy building my app right now and my road map is longer than the chinese wall, but I will get back to you once I have some air. I would love to collab.

> 1. Share your `package.json` so I can match your versions exactly.

Sure this is my package json (sorry I did not really clean in up lately):

```
{
  "name": "mobile",
  "main": "expo-router/entry",
  "version": "0.0.1",
  "scripts": {
    "start": "expo start --reset-cache",
    "start:prod": "expo start --no-dev --minify",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "doctor": "npx expo-doctor@latest",
    "prebuild": "npx expo prebuild",
    "pod:install": "npx pod-install",
    "update:dependencies": "npx expo install --check",
    "eas:ios": "yarn eas:build:ios && yarn eas:submit:ios",
    "eas:build": "eas build",
    "eas:build:all": "eas build --platform all",
    "eas:build:ios": "eas build --platform ios",
    "eas:build:android": "eas build --platform android",
    "eas:submit": "eas submit",
    "eas:submit:all": "eas submit --platform all",
    "eas:submit:ios": "eas submit --platform ios",
    "eas:submit:android": "eas submit --platform android"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/datetimepicker": "8.2.0",
    "@react-native-picker/picker": "^2.11.0",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "@rneui/base": "^4.0.0-rc.8",
    "@rneui/themed": "^4.0.0-rc.8",
    "@shopify/flash-list": "^1.7.3",
    "@supabase/supabase-js": "^2.48.1",
    "eas": "^0.1.0",
    "eslint": "^9.16.0",
    "expo": "^52.0.31",
    "expo-apple-authentication": "7.1.3",
    "expo-av": "15.0.2",
    "expo-background-fetch": "13.0.5",
    "expo-camera": "~16.0.14",
    "expo-constants": "~17.0.5",
    "expo-dev-client": "~5.0.11",
    "expo-device": "~7.0.2",
    "expo-font": "~13.0.3",
    "expo-haptics": "~14.0.1",
    "expo-image-picker": "~16.0.5",
    "expo-insights": "~0.8.2",
    "expo-keep-awake": "~14.0.2",
    "expo-linear-gradient": "~14.0.2",
    "expo-linking": "~7.0.5",
    "expo-notifications": "~0.29.13",
    "expo-router": "~4.0.17",
    "expo-splash-screen": "~0.29.21",
    "expo-sqlite": "~15.0.6",
    "expo-status-bar": "~2.0.1",
    "expo-system-ui": "~4.0.7",
    "expo-task-manager": "~12.0.5",
    "expo-web-browser": "~14.0.2",
    "moment": "^2.30.1",
    "random-animal-name": "^0.1.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.7",
    "react-native-chart-kit": "^6.12.0",
    "react-native-circular-progress": "^1.4.0",
    "react-native-draglist": "^3.6.2",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-get-random-values": "^1.11.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-pagination-ui": "^1.0.4",
    "react-native-picker-select": "^9.1.3",
    "react-native-popup-menu": "^0.16.1",
    "react-native-reanimated": "~3.16.1",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-ruler-picker": "^0.2.2",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-shadow": "^1.2.2",
    "react-native-svg": "15.8.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-timer-picker": "^2.0.2",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-vector-icons": "^10.1.0",
    "react-native-web": "~0.19.11",
    "uuid": "^10.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.5",
    "@types/react": "~18.3.12",
    "@types/uuid": "^10.0.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.3",
    "react-test-renderer": "18.3.1",
    "typescript": "~5.3.3"
  },
  "private": true
}

```

> 2. Let me know if you're on the new architecture or not?

I had the issue before with expo 51 and without the new arch type. But the problem persist with switching to expo 52 and also switching on the new arch type e.g. `"newArchEnabled": true,`

**Comment by troberts-28** [comment]
Thanks for the info!

Somehow I'm still struggling to reproduce this though 😵 I've made an Expo Snack that mirrors your example and setup - can you reproduce it in here? I'm not able to on either an iOS emulator or iOS device.

https://snack.expo.dev/@nuumi/issue-43-demo

> I would love to. But I'm super busy building my app right now and my road map is longer than the chinese wall, but I will get back to you once I have some air. I would love to collab.

Will give you a shout when I get around to taking a look at the generic infinite list library to see if you've got any time to get involved.

And FYI, I released a patch today (v2.0.3) so worth upgrading to that. Unlikely it'll fix this issue but who knows.

**Comment by ssachtleben** [comment]
I downloaded the Snack , run it locally and also cannot reproduce the issue. I guess it's either related to the stack or another dependency causing the issue. I will try to do some more tests as well.

**Comment by troberts-28** [comment]
Hey @ssachtleben, just a heads up that the ability to use the picker fade-out on a transparent background has been added in the recently-released `v2.1.0`

**Comment by ssachtleben** [comment]
Thanks, I cannot reproduce the issue anymore with `v2.1.0` on the simulator. Not sure if it's just coincidence. 

I can give an update on a real device once I pushed the next release.

**Comment by ssachtleben** [comment]
@troberts-28 bug is still there for me 😔

I had no time yet to look further into this. However I needed a date input on another view so I used this lib `@react-native-community/datetimepicker` which basically does the same input behaviour for dates. Works great no vanishing values and feels great but they do not support time input 🙈

It's a pitty there is no generic working lib for all selectable inputs in this form so they all look the same.

I need to look into this further once I have released a first version of my app but right now I need to focus on other topics.

**Comment by troberts-28** [comment]
Hey @ssachtleben,

Frustrating not to have been able to find a solution to this; it must be a pretty specific issue as I haven't had any other reports.

If there isn't a new activity on here in the next 3 weeks, I'm going to close this issue to keep the repo tidy.

**Comment by troberts-28** [comment]
Closing this because of lack of activity 😴
